# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mwindos.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 471)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ed_fold_path = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_fold_path.setGeometry(QtCore.QRect(140, 20, 441, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ed_fold_path.setFont(font)
        self.ed_fold_path.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_fold_path.setObjectName("ed_fold_path")
        self.cb_orig_code = QtWidgets.QComboBox(self.centralwidget)
        self.cb_orig_code.setGeometry(QtCore.QRect(140, 260, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cb_orig_code.setFont(font)
        self.cb_orig_code.setCurrentText("")
        self.cb_orig_code.setMaxVisibleItems(3)
        self.cb_orig_code.setObjectName("cb_orig_code")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 260, 100, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 300, 100, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.cb_exp_code = QtWidgets.QComboBox(self.centralwidget)
        self.cb_exp_code.setGeometry(QtCore.QRect(140, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cb_exp_code.setFont(font)
        self.cb_exp_code.setMaxVisibleItems(3)
        self.cb_exp_code.setObjectName("cb_exp_code")
        self.btn_fold = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fold.setGeometry(QtCore.QRect(20, 20, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_fold.sizePolicy().hasHeightForWidth())
        self.btn_fold.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_fold.setFont(font)
        self.btn_fold.setObjectName("btn_fold")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.ed_cell_type = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_cell_type.setGeometry(QtCore.QRect(140, 70, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ed_cell_type.setFont(font)
        self.ed_cell_type.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_cell_type.setObjectName("ed_cell_type")
        self.btn_Go = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Go.setGeometry(QtCore.QRect(70, 350, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Go.setFont(font)
        self.btn_Go.setObjectName("btn_Go")
        self.ed_cell_key = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_cell_key.setGeometry(QtCore.QRect(140, 120, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ed_cell_key.setFont(font)
        self.ed_cell_key.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_cell_key.setObjectName("ed_cell_key")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.ed_cell_val = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_cell_val.setGeometry(QtCore.QRect(140, 170, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ed_cell_val.setFont(font)
        self.ed_cell_val.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_cell_val.setObjectName("ed_cell_val")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 26))
        self.menubar.setObjectName("menubar")
        self.menuOther = QtWidgets.QMenu(self.menubar)
        self.menuOther.setObjectName("menuOther")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose_Esc = QtWidgets.QAction(MainWindow)
        self.actionClose_Esc.setObjectName("actionClose_Esc")
        self.menuOther.addAction(self.actionClose_Esc)
        self.menubar.addAction(self.menuOther.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_fold, self.btn_Go)
        MainWindow.setTabOrder(self.btn_Go, self.ed_fold_path)
        MainWindow.setTabOrder(self.ed_fold_path, self.ed_cell_type)
        MainWindow.setTabOrder(self.ed_cell_type, self.ed_cell_key)
        MainWindow.setTabOrder(self.ed_cell_key, self.ed_cell_val)
        MainWindow.setTabOrder(self.ed_cell_val, self.cb_orig_code)
        MainWindow.setTabOrder(self.cb_orig_code, self.cb_exp_code)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "批量替换txt画面脚本属性"))
        self.ed_fold_path.setPlaceholderText(_translate("MainWindow", "资源路径"))
        self.label_2.setText(_translate("MainWindow", "原编码"))
        self.label_3.setText(_translate("MainWindow", "预期编码"))
        self.btn_fold.setText(_translate("MainWindow", "选择文件夹"))
        self.label_4.setText(_translate("MainWindow", "元件类型"))
        self.ed_cell_type.setPlaceholderText(_translate("MainWindow", "例：CtmToolButton"))
        self.btn_Go.setText(_translate("MainWindow", "Go"))
        self.ed_cell_key.setPlaceholderText(_translate("MainWindow", "例：wtype"))
        self.label_5.setText(_translate("MainWindow", "元件属性"))
        self.label_6.setText(_translate("MainWindow", "预期属性值"))
        self.ed_cell_val.setPlaceholderText(_translate("MainWindow", "例：0x30，不填则视为删除"))
        self.menuOther.setTitle(_translate("MainWindow", "other(O)"))
        self.actionClose_Esc.setText(_translate("MainWindow", "close (Esc)"))
        self.actionClose_Esc.setShortcut(_translate("MainWindow", "Esc"))

