# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mwindos.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 471)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_rsc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rsc.setGeometry(QtCore.QRect(150, 20, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(11)
        self.lineEdit_rsc.setFont(font)
        self.lineEdit_rsc.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_rsc.setObjectName("lineEdit_rsc")
        self.cb_orig_code = QtWidgets.QComboBox(self.centralwidget)
        self.cb_orig_code.setGeometry(QtCore.QRect(150, 260, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.cb_orig_code.setFont(font)
        self.cb_orig_code.setCurrentText("")
        self.cb_orig_code.setMaxVisibleItems(3)
        self.cb_orig_code.setObjectName("cb_orig_code")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(5, 260, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(5, 300, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.cb_exp_code = QtWidgets.QComboBox(self.centralwidget)
        self.cb_exp_code.setGeometry(QtCore.QRect(150, 300, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.cb_exp_code.setFont(font)
        self.cb_exp_code.setMaxVisibleItems(3)
        self.cb_exp_code.setObjectName("cb_exp_code")
        self.btn_chosefile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_chosefile.setGeometry(QtCore.QRect(5, 20, 140, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_chosefile.sizePolicy().hasHeightForWidth())
        self.btn_chosefile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(15)
        self.btn_chosefile.setFont(font)
        self.btn_chosefile.setObjectName("btn_chosefile")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(5, 70, 140, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_CellType = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CellType.setGeometry(QtCore.QRect(150, 70, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(11)
        self.lineEdit_CellType.setFont(font)
        self.lineEdit_CellType.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_CellType.setObjectName("lineEdit_CellType")
        self.btn_Go = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Go.setGeometry(QtCore.QRect(70, 350, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(20)
        self.btn_Go.setFont(font)
        self.btn_Go.setObjectName("btn_Go")
        self.lineEdit_CellKey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CellKey.setGeometry(QtCore.QRect(150, 120, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(11)
        self.lineEdit_CellKey.setFont(font)
        self.lineEdit_CellKey.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_CellKey.setObjectName("lineEdit_CellKey")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(5, 120, 140, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_CellValue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CellValue.setGeometry(QtCore.QRect(150, 170, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(11)
        self.lineEdit_CellValue.setFont(font)
        self.lineEdit_CellValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_CellValue.setObjectName("lineEdit_CellValue")
        self.btn_ProptyOper = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ProptyOper.setGeometry(QtCore.QRect(5, 170, 140, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ProptyOper.sizePolicy().hasHeightForWidth())
        self.btn_ProptyOper.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(15)
        self.btn_ProptyOper.setFont(font)
        self.btn_ProptyOper.setObjectName("btn_ProptyOper")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 26))
        self.menubar.setObjectName("menubar")
        self.menuOther = QtWidgets.QMenu(self.menubar)
        self.menuOther.setObjectName("menuOther")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose_Esc = QtWidgets.QAction(MainWindow)
        self.actionClose_Esc.setObjectName("actionClose_Esc")
        self.menuOther.addAction(self.actionClose_Esc)
        self.menubar.addAction(self.menuOther.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_chosefile, self.btn_Go)
        MainWindow.setTabOrder(self.btn_Go, self.lineEdit_rsc)
        MainWindow.setTabOrder(self.lineEdit_rsc, self.lineEdit_CellType)
        MainWindow.setTabOrder(self.lineEdit_CellType, self.lineEdit_CellKey)
        MainWindow.setTabOrder(self.lineEdit_CellKey, self.lineEdit_CellValue)
        MainWindow.setTabOrder(self.lineEdit_CellValue, self.cb_orig_code)
        MainWindow.setTabOrder(self.cb_orig_code, self.cb_exp_code)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "批量替换txt画面脚本属性"))
        self.lineEdit_rsc.setPlaceholderText(_translate("MainWindow", "资源路径，例：V:\\XXX\\res_tm640\\form"))
        self.label_2.setText(_translate("MainWindow", "原编码"))
        self.label_3.setText(_translate("MainWindow", "预期编码"))
        self.btn_chosefile.setText(_translate("MainWindow", "选择文件夹"))
        self.label_4.setText(_translate("MainWindow", "元件类型"))
        self.lineEdit_CellType.setPlaceholderText(_translate("MainWindow", "例：CtmToolButton"))
        self.btn_Go.setText(_translate("MainWindow", "Go"))
        self.lineEdit_CellKey.setPlaceholderText(_translate("MainWindow", "例：wtype"))
        self.label_5.setText(_translate("MainWindow", "元件属性"))
        self.lineEdit_CellValue.setPlaceholderText(_translate("MainWindow", "例：0x30，不填则视为删除"))
        self.btn_ProptyOper.setText(_translate("MainWindow", "属性替换/删除"))
        self.menuOther.setTitle(_translate("MainWindow", "other(O)"))
        self.actionClose_Esc.setText(_translate("MainWindow", "close (Esc)"))
        self.actionClose_Esc.setShortcut(_translate("MainWindow", "Esc"))

