# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 256)
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 611, 151))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_progm = QtWidgets.QWidget()
        self.tab_progm.setObjectName("tab_progm")
        self.date = QtWidgets.QLineEdit(self.tab_progm)
        self.date.setGeometry(QtCore.QRect(470, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.date.setFont(font)
        self.date.setObjectName("date")
        self.vers = QtWidgets.QLineEdit(self.tab_progm)
        self.vers.setGeometry(QtCore.QRect(290, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.vers.setFont(font)
        self.vers.setObjectName("vers")
        self.lab_firm = QtWidgets.QLabel(self.tab_progm)
        self.lab_firm.setGeometry(QtCore.QRect(50, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.lab_firm.setFont(font)
        self.lab_firm.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_firm.setObjectName("lab_firm")
        self.firm = QtWidgets.QLineEdit(self.tab_progm)
        self.firm.setGeometry(QtCore.QRect(130, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.firm.setFont(font)
        self.firm.setObjectName("firm")
        self.lab_vers = QtWidgets.QLabel(self.tab_progm)
        self.lab_vers.setGeometry(QtCore.QRect(240, 21, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.lab_vers.setFont(font)
        self.lab_vers.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_vers.setObjectName("lab_vers")
        self.lab_date = QtWidgets.QLabel(self.tab_progm)
        self.lab_date.setGeometry(QtCore.QRect(420, 22, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.lab_date.setFont(font)
        self.lab_date.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_date.setObjectName("lab_date")
        self.progm_store = QtWidgets.QLineEdit(self.tab_progm)
        self.progm_store.setEnabled(True)
        self.progm_store.setGeometry(QtCore.QRect(130, 70, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.progm_store.setFont(font)
        self.progm_store.setObjectName("progm_store")
        self.lab_progm_store = QtWidgets.QLabel(self.tab_progm)
        self.lab_progm_store.setGeometry(QtCore.QRect(0, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.lab_progm_store.setFont(font)
        self.lab_progm_store.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_progm_store.setObjectName("lab_progm_store")
        self.tabWidget.addTab(self.tab_progm, "")
        self.tab_HMI_cfg = QtWidgets.QWidget()
        self.tab_HMI_cfg.setObjectName("tab_HMI_cfg")
        self.HMI_ip = QtWidgets.QLineEdit(self.tab_HMI_cfg)
        self.HMI_ip.setGeometry(QtCore.QRect(100, 20, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.HMI_ip.setFont(font)
        self.HMI_ip.setObjectName("HMI_ip")
        self.lab_passwd = QtWidgets.QLabel(self.tab_HMI_cfg)
        self.lab_passwd.setGeometry(QtCore.QRect(230, 60, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lab_passwd.setFont(font)
        self.lab_passwd.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_passwd.setObjectName("lab_passwd")
        self.HMI_passwd = QtWidgets.QLineEdit(self.tab_HMI_cfg)
        self.HMI_passwd.setGeometry(QtCore.QRect(280, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.HMI_passwd.setFont(font)
        self.HMI_passwd.setObjectName("HMI_passwd")
        self.HMI_port = QtWidgets.QLineEdit(self.tab_HMI_cfg)
        self.HMI_port.setGeometry(QtCore.QRect(480, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.HMI_port.setFont(font)
        self.HMI_port.setObjectName("HMI_port")
        self.lab_port = QtWidgets.QLabel(self.tab_HMI_cfg)
        self.lab_port.setGeometry(QtCore.QRect(420, 60, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lab_port.setFont(font)
        self.lab_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_port.setObjectName("lab_port")
        self.lab_ip = QtWidgets.QLabel(self.tab_HMI_cfg)
        self.lab_ip.setGeometry(QtCore.QRect(20, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lab_ip.setFont(font)
        self.lab_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_ip.setObjectName("lab_ip")
        self.lab_account = QtWidgets.QLabel(self.tab_HMI_cfg)
        self.lab_account.setGeometry(QtCore.QRect(30, 60, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lab_account.setFont(font)
        self.lab_account.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_account.setObjectName("lab_account")
        self.HMI_account = QtWidgets.QLineEdit(self.tab_HMI_cfg)
        self.HMI_account.setGeometry(QtCore.QRect(100, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.HMI_account.setFont(font)
        self.HMI_account.setObjectName("HMI_account")
        self.tabWidget.addTab(self.tab_HMI_cfg, "")
        self.tab_std = QtWidgets.QWidget()
        self.tab_std.setObjectName("tab_std")
        self.lab_progm_res = QtWidgets.QLabel(self.tab_std)
        self.lab_progm_res.setGeometry(QtCore.QRect(30, 19, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_progm_res.setFont(font)
        self.lab_progm_res.setObjectName("lab_progm_res")
        self.progm_res = QtWidgets.QLineEdit(self.tab_std)
        self.progm_res.setEnabled(False)
        self.progm_res.setGeometry(QtCore.QRect(160, 19, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progm_res.setFont(font)
        self.progm_res.setObjectName("progm_res")
        self.shell_path = QtWidgets.QLineEdit(self.tab_std)
        self.shell_path.setEnabled(False)
        self.shell_path.setGeometry(QtCore.QRect(160, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shell_path.setFont(font)
        self.shell_path.setObjectName("shell_path")
        self.lab_shell_path = QtWidgets.QLabel(self.tab_std)
        self.lab_shell_path.setEnabled(True)
        self.lab_shell_path.setGeometry(QtCore.QRect(30, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_shell_path.setFont(font)
        self.lab_shell_path.setObjectName("lab_shell_path")
        self.tabWidget.addTab(self.tab_std, "")
        self.btn_to_pack = QtWidgets.QPushButton(self.centralwidget)
        self.btn_to_pack.setGeometry(QtCore.QRect(530, 170, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.btn_to_pack.setFont(font)
        self.btn_to_pack.setObjectName("btn_to_pack")
        self.pBar = QtWidgets.QProgressBar(self.centralwidget)
        self.pBar.setGeometry(QtCore.QRect(530, 170, 91, 31))
        self.pBar.setProperty("value", 24)
        self.pBar.setTextVisible(False)
        self.pBar.setObjectName("pBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.firm, self.vers)
        MainWindow.setTabOrder(self.vers, self.date)
        MainWindow.setTabOrder(self.date, self.progm_store)
        MainWindow.setTabOrder(self.progm_store, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.HMI_ip)
        MainWindow.setTabOrder(self.HMI_ip, self.HMI_account)
        MainWindow.setTabOrder(self.HMI_account, self.HMI_passwd)
        MainWindow.setTabOrder(self.HMI_passwd, self.HMI_port)
        MainWindow.setTabOrder(self.HMI_port, self.btn_to_pack)
        MainWindow.setTabOrder(self.btn_to_pack, self.shell_path)
        MainWindow.setTabOrder(self.shell_path, self.progm_res)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PLC打包工具"))
        self.lab_firm.setText(_translate("MainWindow", "厂商"))
        self.lab_vers.setText(_translate("MainWindow", "版本"))
        self.lab_date.setText(_translate("MainWindow", "日期"))
        self.lab_progm_store.setText(_translate("MainWindow", "程式存放路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_progm), _translate("MainWindow", "程序信息"))
        self.lab_passwd.setText(_translate("MainWindow", "密码"))
        self.lab_port.setText(_translate("MainWindow", "端口"))
        self.lab_ip.setText(_translate("MainWindow", "面板IP"))
        self.lab_account.setText(_translate("MainWindow", "账号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_HMI_cfg), _translate("MainWindow", "目标面板配置"))
        self.lab_progm_res.setText(_translate("MainWindow", "程式来源路径"))
        self.progm_res.setText(_translate("MainWindow", "面板 \\usr路径下"))
        self.shell_path.setText(_translate("MainWindow", "面板 \\usr路径下"))
        self.lab_shell_path.setText(_translate("MainWindow", "shell存放路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_std), _translate("MainWindow", "其他配置参考"))
        self.btn_to_pack.setText(_translate("MainWindow", "开始打包"))
