# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkRstTab.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rst(object):
    def setupUi(self, rst):
        rst.setObjectName("rst")
        rst.resize(1021, 656)
        self.tabWidget = QtWidgets.QTabWidget(rst)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1000, 630))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTitleID = QtWidgets.QWidget()
        self.tabTitleID.setObjectName("tabTitleID")
        self.listViewTitleID = QtWidgets.QListView(self.tabTitleID)
        self.listViewTitleID.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.listViewTitleID.setFont(font)
        self.listViewTitleID.setObjectName("listViewTitleID")
        self.tabWidget.addTab(self.tabTitleID, "")
        self.tabSo = QtWidgets.QWidget()
        self.tabSo.setObjectName("tabSo")
        self.listViewSo = QtWidgets.QListView(self.tabSo)
        self.listViewSo.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.listViewSo.setFont(font)
        self.listViewSo.setObjectName("listViewSo")
        self.tabWidget.addTab(self.tabSo, "")
        self.tabTaborder = QtWidgets.QWidget()
        self.tabTaborder.setObjectName("tabTaborder")
        self.listViewTaborder = QtWidgets.QListView(self.tabTaborder)
        self.listViewTaborder.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.listViewTaborder.setFont(font)
        self.listViewTaborder.setObjectName("listViewTaborder")
        self.tabWidget.addTab(self.tabTaborder, "")
        self.tabPwnd = QtWidgets.QWidget()
        self.tabPwnd.setObjectName("tabPwnd")
        self.listViewPwnd = QtWidgets.QListView(self.tabPwnd)
        self.listViewPwnd.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.listViewPwnd.setFont(font)
        self.listViewPwnd.setObjectName("listViewPwnd")
        self.tabWidget.addTab(self.tabPwnd, "")
        self.tabDBID0 = QtWidgets.QWidget()
        self.tabDBID0.setObjectName("tabDBID0")
        self.tableWidgetDBID0 = QtWidgets.QTableWidget(self.tabDBID0)
        self.tableWidgetDBID0.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        self.tableWidgetDBID0.setObjectName("tableWidgetDBID0")
        self.tableWidgetDBID0.setColumnCount(0)
        self.tableWidgetDBID0.setRowCount(0)
        self.tabWidget.addTab(self.tabDBID0, "")

        self.retranslateUi(rst)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(rst)

    def retranslateUi(self, rst):
        _translate = QtCore.QCoreApplication.translate
        rst.setWindowTitle(_translate("rst", "验证结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTitleID), _translate("rst", "titleID丢失"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSo), _translate("rst", "so丢失"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTaborder), _translate("rst", "taborder重复"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPwnd), _translate("rst", "元件名重复"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDBID0), _translate("rst", "dbid0重复"))

