# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formCheck.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 285)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 60, 151, 111))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.cbxSo = QtWidgets.QCheckBox(self.groupBox)
        self.cbxSo.setEnabled(False)
        self.cbxSo.setGeometry(QtCore.QRect(20, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.cbxSo.setFont(font)
        self.cbxSo.setChecked(True)
        self.cbxSo.setObjectName("cbxSo")
        self.ckbTitleID = QtWidgets.QCheckBox(self.groupBox)
        self.ckbTitleID.setEnabled(False)
        self.ckbTitleID.setGeometry(QtCore.QRect(20, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.ckbTitleID.setFont(font)
        self.ckbTitleID.setChecked(True)
        self.ckbTitleID.setObjectName("ckbTitleID")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 60, 151, 111))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.ckbTab = QtWidgets.QCheckBox(self.groupBox_2)
        self.ckbTab.setEnabled(False)
        self.ckbTab.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.ckbTab.setFont(font)
        self.ckbTab.setCheckable(True)
        self.ckbTab.setChecked(True)
        self.ckbTab.setObjectName("ckbTab")
        self.ckbTab_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.ckbTab_2.setEnabled(False)
        self.ckbTab_2.setGeometry(QtCore.QRect(20, 50, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.ckbTab_2.setFont(font)
        self.ckbTab_2.setCheckable(True)
        self.ckbTab_2.setChecked(True)
        self.ckbTab_2.setObjectName("ckbTab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 60, 151, 111))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.ckbDBID0 = QtWidgets.QCheckBox(self.groupBox_3)
        self.ckbDBID0.setEnabled(False)
        self.ckbDBID0.setGeometry(QtCore.QRect(20, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.ckbDBID0.setFont(font)
        self.ckbDBID0.setObjectName("ckbDBID0")
        self.pbtCheck = QtWidgets.QPushButton(self.centralwidget)
        self.pbtCheck.setGeometry(QtCore.QRect(20, 180, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.pbtCheck.setFont(font)
        self.pbtCheck.setObjectName("pbtCheck")
        self.pbtCfg = QtWidgets.QPushButton(self.centralwidget)
        self.pbtCfg.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.pbtCfg.setFont(font)
        self.pbtCfg.setObjectName("pbtCfg")
        self.edCfg = QtWidgets.QLineEdit(self.centralwidget)
        self.edCfg.setGeometry(QtCore.QRect(110, 20, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(10)
        self.edCfg.setFont(font)
        self.edCfg.setObjectName("edCfg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 26))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuMain.addAction(self.actionClose)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HMI画面脚本验证器"))
        self.groupBox.setTitle(_translate("MainWindow", "判断存在"))
        self.cbxSo.setText(_translate("MainWindow", "so"))
        self.ckbTitleID.setText(_translate("MainWindow", "titleID"))
        self.groupBox_2.setTitle(_translate("MainWindow", "判断重复"))
        self.ckbTab.setText(_translate("MainWindow", "元件名"))
        self.ckbTab_2.setText(_translate("MainWindow", "taborder"))
        self.groupBox_3.setTitle(_translate("MainWindow", "判断全局重复"))
        self.ckbDBID0.setText(_translate("MainWindow", "dbid0"))
        self.pbtCheck.setText(_translate("MainWindow", "开始验证"))
        self.pbtCfg.setText(_translate("MainWindow", "选择config"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Esc"))

