# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(517, 219)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ed_565 = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_565.setGeometry(QtCore.QRect(80, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.ed_565.setFont(font)
        self.ed_565.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_565.setObjectName("ed_565")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ed_888 = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_888.setGeometry(QtCore.QRect(80, 70, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.ed_888.setFont(font)
        self.ed_888.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_888.setObjectName("ed_888")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ed_RGB = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_RGB.setGeometry(QtCore.QRect(80, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.ed_RGB.setFont(font)
        self.ed_RGB.setAlignment(QtCore.Qt.AlignCenter)
        self.ed_RGB.setObjectName("ed_RGB")
        self.btn_ShowColor = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ShowColor.setGeometry(QtCore.QRect(260, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        self.btn_ShowColor.setFont(font)
        self.btn_ShowColor.setAutoFillBackground(True)
        self.btn_ShowColor.setObjectName("btn_ShowColor")
        self.lb_ShowColor = QtWidgets.QLabel(self.centralwidget)
        self.lb_ShowColor.setGeometry(QtCore.QRect(280, 90, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(15)
        self.lb_ShowColor.setFont(font)
        self.lb_ShowColor.setAutoFillBackground(True)
        self.lb_ShowColor.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_ShowColor.setObjectName("lb_ShowColor")
        self.btn_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cancel.setGeometry(QtCore.QRect(390, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        self.btn_Cancel.setFont(font)
        self.btn_Cancel.setAutoFillBackground(True)
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.chkbox_dec = QtWidgets.QCheckBox(self.centralwidget)
        self.chkbox_dec.setEnabled(False)
        self.chkbox_dec.setGeometry(QtCore.QRect(260, 60, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.chkbox_dec.setFont(font)
        self.chkbox_dec.setObjectName("chkbox_dec")
        self.chkbox_hex = QtWidgets.QCheckBox(self.centralwidget)
        self.chkbox_hex.setEnabled(False)
        self.chkbox_hex.setGeometry(QtCore.QRect(390, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.chkbox_hex.setFont(font)
        self.chkbox_hex.setObjectName("chkbox_hex")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 26))
        self.menubar.setObjectName("menubar")
        self.menuOther_O = QtWidgets.QMenu(self.menubar)
        self.menuOther_O.setObjectName("menuOther_O")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionHelp_doc = QtWidgets.QAction(MainWindow)
        self.actionHelp_doc.setObjectName("actionHelp_doc")
        self.menuOther_O.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionHelp_doc)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuOther_O.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_Cancel.clicked.connect(self.ed_565.clear)
        self.btn_Cancel.clicked.connect(self.ed_888.clear)
        self.btn_Cancel.clicked.connect(self.ed_RGB.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_ShowColor, self.btn_Cancel)
        MainWindow.setTabOrder(self.btn_Cancel, self.ed_565)
        MainWindow.setTabOrder(self.ed_565, self.ed_888)
        MainWindow.setTabOrder(self.ed_888, self.chkbox_dec)
        MainWindow.setTabOrder(self.chkbox_dec, self.chkbox_hex)
        MainWindow.setTabOrder(self.chkbox_hex, self.ed_RGB)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "R G B"))
        self.label_5.setText(_translate("MainWindow", "RGB565"))
        self.label_6.setText(_translate("MainWindow", "RGB888"))
        self.btn_ShowColor.setText(_translate("MainWindow", "确认"))
        self.lb_ShowColor.setText(_translate("MainWindow", "颜色将在此显示"))
        self.btn_Cancel.setText(_translate("MainWindow", "清除"))
        self.chkbox_dec.setText(_translate("MainWindow", "十进制"))
        self.chkbox_hex.setText(_translate("MainWindow", "十六进制"))
        self.menuOther_O.setTitle(_translate("MainWindow", "other(O)"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help(H)"))
        self.actionClose.setText(_translate("MainWindow", "close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Esc"))
        self.actionHelp_doc.setText(_translate("MainWindow", "help doc"))
        self.actionHelp_doc.setShortcut(_translate("MainWindow", "Alt+H"))

