# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(468, 301)
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        Form.setFont(font)
        self.label_Month = QtWidgets.QLabel(Form)
        self.label_Month.setGeometry(QtCore.QRect(200, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Month.setFont(font)
        self.label_Month.setObjectName("label_Month")
        self.label_day = QtWidgets.QLabel(Form)
        self.label_day.setGeometry(QtCore.QRect(280, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_day.setFont(font)
        self.label_day.setObjectName("label_day")
        self.label_Year = QtWidgets.QLabel(Form)
        self.label_Year.setGeometry(QtCore.QRect(390, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Year.setFont(font)
        self.label_Year.setObjectName("label_Year")
        self.label_VaildDate = QtWidgets.QLabel(Form)
        self.label_VaildDate.setGeometry(QtCore.QRect(10, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_VaildDate.setFont(font)
        self.label_VaildDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_VaildDate.setObjectName("label_VaildDate")
        self.label_FeatureCode = QtWidgets.QLabel(Form)
        self.label_FeatureCode.setGeometry(QtCore.QRect(10, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_FeatureCode.setFont(font)
        self.label_FeatureCode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FeatureCode.setObjectName("label_FeatureCode")
        self.pushButton_AuthorizedCode = QtWidgets.QPushButton(Form)
        self.pushButton_AuthorizedCode.setGeometry(QtCore.QRect(30, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_AuthorizedCode.setFont(font)
        self.pushButton_AuthorizedCode.setObjectName("pushButton_AuthorizedCode")
        self.label_FeatureCode_2 = QtWidgets.QLabel(Form)
        self.label_FeatureCode_2.setGeometry(QtCore.QRect(70, 250, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_FeatureCode_2.setFont(font)
        self.label_FeatureCode_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_FeatureCode_2.setObjectName("label_FeatureCode_2")
        self.lineEdit_AuthorizedCode = QtWidgets.QLineEdit(Form)
        self.lineEdit_AuthorizedCode.setGeometry(QtCore.QRect(150, 160, 201, 31))
        self.lineEdit_AuthorizedCode.setMaxLength(14)
        self.lineEdit_AuthorizedCode.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_AuthorizedCode.setObjectName("lineEdit_AuthorizedCode")
        self.lineEdit_FeatureCode = QtWidgets.QLineEdit(Form)
        self.lineEdit_FeatureCode.setGeometry(QtCore.QRect(150, 110, 201, 31))
        self.lineEdit_FeatureCode.setMaxLength(12)
        self.lineEdit_FeatureCode.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FeatureCode.setObjectName("lineEdit_FeatureCode")
        self.lineEdit_Month = QtWidgets.QLineEdit(Form)
        self.lineEdit_Month.setGeometry(QtCore.QRect(150, 50, 41, 31))
        self.lineEdit_Month.setMaxLength(2)
        self.lineEdit_Month.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Month.setObjectName("lineEdit_Month")
        self.lineEdit_Day = QtWidgets.QLineEdit(Form)
        self.lineEdit_Day.setGeometry(QtCore.QRect(230, 50, 41, 31))
        self.lineEdit_Day.setMaxLength(2)
        self.lineEdit_Day.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Day.setObjectName("lineEdit_Day")
        self.lineEdit_Year = QtWidgets.QLineEdit(Form)
        self.lineEdit_Year.setGeometry(QtCore.QRect(310, 50, 71, 31))
        self.lineEdit_Year.setMaxLength(4)
        self.lineEdit_Year.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Year.setObjectName("lineEdit_Year")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_Month, self.lineEdit_Day)
        Form.setTabOrder(self.lineEdit_Day, self.lineEdit_Year)
        Form.setTabOrder(self.lineEdit_Year, self.lineEdit_FeatureCode)
        Form.setTabOrder(self.lineEdit_FeatureCode, self.pushButton_AuthorizedCode)
        Form.setTabOrder(self.pushButton_AuthorizedCode, self.lineEdit_AuthorizedCode)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "授权码计算（win7及以上）"))
        self.label_Month.setText(_translate("Form", "月"))
        self.label_day.setText(_translate("Form", "日"))
        self.label_Year.setText(_translate("Form", "年"))
        self.label_VaildDate.setText(_translate("Form", "开通Go功能的日期"))
        self.label_FeatureCode.setText(_translate("Form", "特征码"))
        self.pushButton_AuthorizedCode.setText(_translate("Form", "授权码计算"))
        self.pushButton_AuthorizedCode.setShortcut(_translate("Form", "Enter"))
        self.label_FeatureCode_2.setText(_translate("Form", "仅限内部交流使用 -- Chenly"))
        self.lineEdit_AuthorizedCode.setPlaceholderText(_translate("Form", "CopyOnly"))
        self.lineEdit_FeatureCode.setPlaceholderText(_translate("Form", "12码"))
        self.lineEdit_Month.setText(_translate("Form", "1"))
        self.lineEdit_Day.setText(_translate("Form", "1"))
        self.lineEdit_Year.setText(_translate("Form", "2018"))
        self.lineEdit_Year.setPlaceholderText(_translate("Form", "在此输入12码授权码"))

