# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 383)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Other = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Other.setEnabled(False)
        self.pushButton_Other.setGeometry(QtCore.QRect(20, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.pushButton_Other.setFont(font)
        self.pushButton_Other.setCheckable(False)
        self.pushButton_Other.setObjectName("pushButton_Other")
        self.pushButton_55_270 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_55_270.setGeometry(QtCore.QRect(20, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.pushButton_55_270.setFont(font)
        self.pushButton_55_270.setCheckable(False)
        self.pushButton_55_270.setObjectName("pushButton_55_270")
        self.lineEdit_55_270 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_55_270.setEnabled(False)
        self.lineEdit_55_270.setGeometry(QtCore.QRect(180, 70, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.lineEdit_55_270.setFont(font)
        self.lineEdit_55_270.setObjectName("lineEdit_55_270")
        self.lineEdit_55_3354 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_55_3354.setEnabled(False)
        self.lineEdit_55_3354.setGeometry(QtCore.QRect(180, 120, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.lineEdit_55_3354.setFont(font)
        self.lineEdit_55_3354.setObjectName("lineEdit_55_3354")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_54.setEnabled(False)
        self.lineEdit_54.setGeometry(QtCore.QRect(180, 20, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.lineEdit_54.setFont(font)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_Other = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Other.setEnabled(False)
        self.lineEdit_Other.setGeometry(QtCore.QRect(180, 170, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.lineEdit_Other.setFont(font)
        self.lineEdit_Other.setObjectName("lineEdit_Other")
        self.pushButton_54 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_54.setGeometry(QtCore.QRect(20, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setCheckable(False)
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55_3354 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_55_3354.setGeometry(QtCore.QRect(20, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.pushButton_55_3354.setFont(font)
        self.pushButton_55_3354.setCheckable(False)
        self.pushButton_55_3354.setObjectName("pushButton_55_3354")
        self.label_Prompt = QtWidgets.QLabel(self.centralwidget)
        self.label_Prompt.setGeometry(QtCore.QRect(20, 230, 641, 40))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(20)
        self.label_Prompt.setFont(font)
        self.label_Prompt.setAccessibleName("")
        self.label_Prompt.setObjectName("label_Prompt")
        self.label_images = QtWidgets.QLabel(self.centralwidget)
        self.label_images.setGeometry(QtCore.QRect(460, 210, 231, 121))
        self.label_images.setText("")
        self.label_images.setObjectName("label_images")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Other.setText(_translate("MainWindow", "其他"))
        self.pushButton_55_270.setText(_translate("MainWindow", "55_270_M12"))
        self.lineEdit_55_270.setText(_translate(
            "MainWindow", "W:/pxammi/7HT_M12_DSP55/res_tm640/font/test_v8/"))
        self.lineEdit_55_3354.setText(_translate(
            "MainWindow", "V:/pxammi/7HT_3354_M12/res_tm640/font/test_v8/"))
        self.lineEdit_54.setText(_translate(
            "MainWindow", "W:/pxammi/7HT_PXA270_M12_1895ToZyh/res_tm640/font/test_v8/"))
        self.pushButton_54.setText(_translate("MainWindow", "54"))
        self.pushButton_55_3354.setText(_translate("MainWindow", "55_3354"))
        self.label_Prompt.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">进度</span></p></body></html>"))
